/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
	export interface GlobalComponents {
		Alert: (typeof import('./components/Alert.vue'))['default'];
		AppFooter: (typeof import('./components/AppFooter.vue'))['default'];
		HelloWorld: (typeof import('./components/HelloWorld.vue'))['default'];
		Loader: (typeof import('./components/Loader.vue'))['default'];
		OrderNotFound: (typeof import('./components/OrderNotFound.vue'))['default'];
		QRCode: (typeof import('./components/QRCode.vue'))['default'];
		RouterLink: (typeof import('vue-router'))['RouterLink'];
		RouterView: (typeof import('vue-router'))['RouterView'];
	}
}
