/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/ui/Alert.vue')['default']
    AppBar: typeof import('./components/layout/AppBar.vue')['default']
    DeliveryDataForm: typeof import('./components/forms/DeliveryDataForm.vue')['default']
    ImageSlider: typeof import('./components/ImageSlider.vue')['default']
    Loader: typeof import('./components/ui/Loader.vue')['default']
    NotFound: typeof import('./components/ui/NotFound.vue')['default']
    OfferCard: typeof import('./components/offer/OfferCard.vue')['default']
    OfferInfo: typeof import('./components/offer/OfferInfo.vue')['default']
    OrderNotFound: typeof import('./components/OrderNotFound.vue')['default']
    PaymentDataForm: typeof import('./components/forms/PaymentDataForm.vue')['default']
    PersonalDataForm: typeof import('./components/forms/PersonalDataForm.vue')['default']
    QRCode: typeof import('./components/QRCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
